### ISSUE TITLE
the bug

### ISSUE THREAD

**Issue by arnold-em** [dungdx34/MTGNN-SUM#2]
sorry sir bother you again,
there have some problems:
Traceback (most recent call last):
  File "train.py", line 379, in <module>
    main()
  File "train.py", line 340, in main
    pretrained_weight = embed_loader.add_unknown_words_by_avg(vectors, args.word_emb_dim)
  File "/home/cht/cht/MTGNN/MTGNN-SUM-main/module/embedding.py", line 85, in add_unknown_words_by_avg
    avg = col[m] / int(len(word_vecs_numpy))
ZeroDivisionError: float division by zero

**Comment by dungdx34** [comment]
Please download the glove embedding file to the source folder.

**Comment by arnold-em** [comment]
thanks，
i found the issue already，
and you my friend，you are the real hero！



At 2022-10-31 07:05:17, "BlueSky" ***@***.***> wrote:

Please download the glove embedding file to the source folder.
